### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by yangt235** [vdevauxchupin/ITS-LIVE-Downloader-Tracker#2]
(https://user-images.githubusercontent.com/88574896/204142820-ac7a9810-b028-4675-9eb8-a51f43f58915.png)
Hello, I downloaded the above mentioned area, and he reported the following error.

(
OverflowError                             Traceback (most recent call last)
File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:372, in pandas._libs.tslibs.timedeltas._maybe_cast_from_unit()

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\_libs\tslibs\conversion.pyx:126, in pandas._libs.tslibs.conversion.cast_from_unit()

OverflowError: int too big to convert

The above exception was the direct cause of the following exception:

OutOfBoundsTimedelta                      Traceback (most recent call last)
File ~\anaconda3\envs\Glaciervel\lib\site-packages\xarray\coding\times.py:275, in decode_cf_datetime(num_dates, units, calendar, use_cftime)
    274 try:
--> 275     dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    276 except (KeyError, OutOfBoundsDatetime, OutOfBoundsTimedelta, OverflowError):

File ~\anaconda3\envs\Glaciervel\lib\site-packages\xarray\coding\times.py:228, in _decode_datetime_with_pandas(flat_num_dates, units, calendar)
    226 if flat_num_dates.size > 0:
    227     # avoid size 0 datetimes GH1329
--> 228     pd.to_timedelta(flat_num_dates.min(), delta) + ref_date
    229     pd.to_timedelta(flat_num_dates.max(), delta) + ref_date

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\core\tools\timedeltas.py:211, in to_timedelta(arg, unit, errors)
    210 # ...so it must be a scalar value. Return scalar.
--> 211 return _coerce_scalar_to_timedelta_type(arg, unit=unit, errors=errors)

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\core\tools\timedeltas.py:219, in _coerce_scalar_to_timedelta_type(r, unit, errors)
    218 try:
--> 219     result = Timedelta(r, unit)
    220 except ValueError:

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:1695, in pandas._libs.tslibs.timedeltas.Timedelta.__new__()

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:351, in pandas._libs.tslibs.timedeltas.convert_to_timedelta64()

File ~\anaconda3\envs\Glaciervel\lib\site-packages\pandas\_libs\tslibs\timedeltas.pyx:374, in pandas._libs.tslibs.timedeltas._maybe_cast_from_unit()

OutOfBoundsTimedelta: Cannot cast -1.2913510797440406e+308 from D to 'ns' without overflow.

During handling of the above exception, another exception occurred:

.....

OverflowError: time values outside range of 64 bit signed integers
)
I wonder if it's because I've chosen too large an area. 
I hope you can give me some help. Thank you

**Comment by vdevauxchupin** [comment]
Hi @yangt235,

From the error code it seems that it could come from the timedelta being too big (maybe sdate and edate variables are too far apart ?). Could you tell me:

- Are you using the code from Binder, or did you download it on your personal machine ? 
- What are your sdate and edate ?
- What is your 'type_dataset' variable ? 
- What is your 'TYPE' variable ? 
- What is your 'amount' variable ?

I will try to reproduce the error and solve it. Thank you for reporting it !

**Comment by yangt235** [comment]
Thanks for your help.
 
 I downloaded it from your github and  followed your instructions to complete the corresponding configuration.
sdate = '2014-01-01',  edate = '2015-01-01',  type_dataset: "Subyearly", threshold = 40,
variables_to_keep = ['vx','vy', 'v', 'v_error', 'date_dt','date_center', 'satellite_img1'].

**Comment by vdevauxchupin** [comment]
I'm tried to replicate the issue but couldn't manage to do it. I downloaded for the following area: 
![image](https://user-images.githubusercontent.com/73993845/204408387-4addfa6d-98eb-4fcb-b4e8-9c73e058ae5f.png)

Did you manage to download some of the files ? From your pictures, I assume your area of interest is overlapping 3 datacubes. 
If yes, could you send me a screenshot of how many files you have and their size ? (see below)
![image](https://user-images.githubusercontent.com/73993845/204408435-05b7aa49-35d7-4c63-82ef-60112ab29f83.png)

If the files are too large, the blocking factor will be your RAM. I suggest to monitor how much RAM is used during the downloading. Max RAM usage happens when the files are saved to the computer as netCDFs. 

**To reduce the memory size**, the best option is to fragment your date into smaller chunks. To do that:

1. Change to date to: sdate = '2014-01-01' and edate = '2014-06-01' (for example)
2. Choose your AOI, select one point in each cube overlapped by the AOI, click on 'Get Points', then 'Export Data'
3. Once the download is finished, come back to the cell where you choose your dates, and change them to: sdate = '2014-06-02' and edate = '2015-01-01'.
4. Run the cell again to get the changes in memory.
5. Then, click directly on the 'Export Data' button

It will download the same datacubes with the same extent as before, but with the new dates. It will save them automatically in the same folder, therefore when you run the Tracker notebook you don't need to change anything. 


To me that's the best option, because you don't sacrifice the quality of your dataset, it just takes a bit more time to get the data. However you can always reduce your AOI or increase the 'threshold' variable, but I would advise to at least try smaller date chunks before. 

Let me know if that solves your issue ! If not I don't see where it's coming from because I can't replicate the problem.

**Comment by yangt235** [comment]
Thanks for your constructive suggestions. I feel more and more that the problem is caused by my memory. Thank you for developing this handy tool.I can now download some small scale and time data.

**Comment by vdevauxchupin** [comment]
Thank you for your feedback !! I will leave the issue open for a few more days, let me know if you still encounter the same issue after reducing the size of the datacubes.
